some-example-chart:
  service:    
    resources: 
      limits:
        cpu: 100m
        memory: 100Mi
      replicaCount: 2
  job:
    resources: 
      limits:
        cpu: 100m
        memory: 100Mi
      replicaCount: 2
