{{- $uniqueValue := sha256sum .Values.uniqueValue  -}}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ printf "%.39s-job" .Release.Name | trunc 44 }}
  annotations:
    argocd.argoproj.io/sync-wave: '1'
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    job-name: {{ printf "%.39s-job" .Release.Name | trunc 44 }}
    checksum/config: {{ $uniqueValue }}
spec:
  activeDeadlineSeconds: {{ .Values.job.timeout }}
  backoffLimit: {{ .Values.job.retries }}
  template:
    metadata:
      name: job
      labels:
        app: job
    spec:
      restartPolicy: Never
      containers:
      - name: job
        image: {{ .Values.imageName }}
        imagePullPolicy: IfNotPresent

        {{- with .Values.job.commandArgs }}
        args: {{ toJson . }}
        {{- end }}
        {{- with .Values.job.command }}
        command: {{ toJson . }}
        {{- end }}

        env:
        - name: {{ .Values.jobOutputFileEnvVar }}
          value: {{ printf "/mnt/job-outputs/%s-%s" .Release.Name $uniqueValue}}

        resources:
          limits:
            cpu: 10m
            memory: 32Mi  

        volumeMounts:
         - name: job-outputs
           mountPath: /mnt/job-outputs

      volumes:
        - name: job-outputs
          persistentVolumeClaim:
            claimName: common-pvc