apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: openshift-gitops
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  generators:
    - git: #Apps
        repoURL: 'https://github.com/danielmarom78/discount-general.git'
        revision: HEAD
        directories:
        - path: 'uat/*'              
        pathParamPrefix: app  
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: envLabel
              operator: NotIn
              values:
                - xxx
          maxUpdate: 1%      
  template:  
    metadata:
      name: '{{path.basenameNormalized}}'
      labels:
        envLabel: 'env-uat'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danielmarom78/discount-appset.git'
        targetRevision: HEAD
        path: '{{app.path.path}}'
        helm:
          valuesObject:
            some-example-chart:                     
              uniqueValue: TRIGGER-BY-CHANGING-NEW
          valueFiles: 
            - '{../{envValues.yaml}}' #EnvValues
            - '{{{Values.yaml}}' #AppValues
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'discount'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true