apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: openshift-gitops
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  generators:
    - git: 
        repoURL: 'https://github.com/danielmarom78/discount-general.git'
        revision: HEAD
        directories:
        - path: 'uat/*'              
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
                - env-uat
          maxUpdate: 10%      
  template:  
    metadata:
      name: '{{path.basenameNormalized}}'
      labels:
        envLabel: env-uat
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danielmarom78/discount-general.git'
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles: 
            - '../envValues.yaml' #EnvValues
            - 'values.yaml' #AppValues
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'discount'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true