argoNamespace: openshift-gitops # Namespace managed by argocd
argoProject: default # ArgoCD AppProject where apps will be created

namespace: discount # destination namespace for the workloads


# Helm/Git location for the app of apps
service:
  repoURL: https://github.com/danielmarom78/discount.git # RepoURL is the URL to the repository (Git or Helm)
  revision: main   # tag / branch / semver


pvcSize: 50Mi # Small PVC - each service will write a timestamp file for each rollout
pvcStorageClass: managed-nfs-storage # RWX storage class for moving files between jobs and services

quota:
  limits.cpu: 8
  limits.memory: 8Gi
  #requests.cpu:
  #requests.memory:
  
env: uat
repoURL: https://github.com/danielmarom78/discount-general.git