some-example-chart:
  uniqueValue: 'applicationUniqueValue'
  service:    
    resources: 
      limits:
        cpu: 100m
        memory: 100Mi
  job:
    resources: 
      limits:
        cpu: 100m
        memory: 100Mi
